/* Grammar 2 content (embedded as-is).
   English lines must remain unchanged. */
(function () {
  window.__G2_DATA__ = [
    {
      id: "g2_01_be_am_is_are",
      title: "1. Grammar be (am/is/are)",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar be (am/is/are)",
            "TO BE",
            "AFFIRMATIVE FORM (+)",
            "FULL FORM:",
            "I am",
            "You are",
            "He / She / It is",
            "We / You / They are",
            "SHORT FORM:",
            "I 'm",
            "You 're",
            "He / She / It 's",
            "We / You / They 're",
            "NEGATIVE FORM (-)",
            "FULL FORM:",
            "I am not",
            "You are not",
            "He / She / It is not",
            "We / You / They are not",
            "SHORT FORM (1):",
            "I 'm not",
            "You 're not",
            "He / She / It 's not",
            "We / You / They 're not",
            "SHORT FORM (2):",
            "I 'm not",
            "You aren't",
            "He / She / It isn't",
            "We / You / They aren't",
            "INTERROGATIVE FORM",
            "Am I South African?",
            "Are you a football player?",
            "Is he/she/it tall?",
            "Are we hardworking?",
            "Are you popular?",
            "Are they at home?",
            "EXAMPLES (E.g.)",
            "I am a teacher.",
            "They aren't singers.",
            "It is cute.",
            "You are not sick.",
            "He is not feeling well.",
            "She isn't a doctor.",
            "Are they from Tanzania?",
            "Am I at the cinema?",
            "Languages are not difficult.",
            "Is Polish easy?",
            "Are you ok?",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- فعل (to be) يستخدم في الحاضر للتعبير عن: الحالة/الصفة/الهوية/المكان.",
            "",
            "الصيغة المثبتة (Affirmative):",
            "- Subject + am/is/are",
            "اختيار الفعل حسب الفاعل:",
            "- I → am",
            "- He/She/It → is",
            "- You/We/They → are",
            "",
            "الصيغة المنفية (Negative):",
            "- Full form: Subject + am/is/are + not",
            "- Short form: I'm not / isn't / aren't (حسب الفاعل)",
            "ملاحظة مهمة (مثل الملف):",
            "- مع I الاختصار الشائع: I'm not (ولا يوجد aren't مع I).",
            "",
            "صيغة السؤال (Interrogative):",
            "- ? Am/Is/Are + Subject + Complement",
            "ملاحظة:",
            "- في أسئلة Wh- (Where/What...) نضع كلمة السؤال أولاً ثم نتبع نفس ترتيب السؤال.",
            "",
            "ملخص سريع:",
            "- I am (I’m) / I am not (I’m not) / Am I…?",
            "- He is (He’s) / He is not (He isn’t) / Is he…?",
            "- They are (They’re) / They are not (They aren’t) / Are they…?",
          ],
        },
      ],
    },
    {
      id: "g2_02_possessive",
      title: "2. Possessive 's and possessive adjectives (Source A)",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar: Possessive 's and possessive adjectives",
            "POSSESSIVE ADJECTIVES",
            "Subject Pronoun + verb:",
            "I",
            "You",
            "He",
            "She",
            "It",
            "We",
            "You",
            "They",
            "Example: I am a teacher.",
            "Possessive Adjective + noun:",
            "my",
            "your",
            "his",
            "her",
            "its",
            "our",
            "your",
            "their",
            "Example: These are my shoes.",
            "Source: 7ESL.COM",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 الفكرة العامة:",
            "- Possessive Adjectives (my/your/his/her/its/our/their) تأتي قبل الاسم لتوضح لمن الشيء.",
            "",
            "🧠 متى نستخدمها؟",
            "- عندما نريد قول: (حذائي/كتابك/سيارتهم...) في الإنجليزية.",
            "",
            "🧩 القاعدة الأساسية:",
            "- Possessive Adjective + Noun",
            "- مثال من الدرس: These are my shoes.",
            "",
            "✅ تحويل سريع (ضمير → صفة ملكية):",
            "- I → my",
            "- you → your",
            "- he → his",
            "- she → her",
            "- it → its",
            "- we → our",
            "- they → their",
            "",
            "⚠️ أخطاء شائعة:",
            "- الخلط بين its (ملكية) و it's (اختصار it is) ❗ (هذه ملاحظة توضيحية لأن الدرس يعرض its ضمن القائمة).",
            "",
            "فكرة تثبيت: إذا جاءت my/your… توقّع بعدها اسم مباشرة.",
          ],
        },
        { k: "SRC", lines: ["Source: 7ESL.COM"] },
      ],
    },
    {
      id: "g2_03_and_but",
      title: "3. Writing Skill and / but (Source A)",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Writing Skill and/ but",
            "Grammar Quickies",
            "COORDINATING CONJUNCTIONS 101",
            "and: links similar (or like) ideas.",
            "I like apples and bananas.",
            "or: links alternative ideas.",
            "Do you want an apple or a banana?",
            "but: links contrasting ideas.",
            "I like apples but I don't like bananas.",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 الفكرة العامة:",
            "- and / or / but روابط تنسيقية تربط فكرتين في نفس الجملة.",
            "",
            "🧠 متى أستخدم كل رابط؟",
            "- and: إضافة فكرة مشابهة أو شيء إضافي.",
            "- or: اختيار/بديل بين شيئين.",
            "- but: تعارض أو اختلاف بين فكرتين.",
            "",
            "🧩 طريقة تمييز سريعة:",
            "- اسأل نفسك: (أضيف؟ أختار؟ أعكس؟) ثم اختر الرابط.",
            "",
            "⚠️ خطأ شائع:",
            "- استخدام but بدل and أو العكس في جملة لا يوجد فيها تعارض.",
            "",
            "فكرة تثبيت: and إضافة — or خيار — but عكس.",
          ],
        },
      ],
    },
    {
      id: "g2_04_there_is_are",
      title: "4. Grammar There is / there are",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar There is/are",
            "Meaning: To say that something exists (or doesn't exist)",
            "AFFIRMATIVE:",
            "There is + singular noun -> There is a book on the desk.",
            "There are + plural noun -> There are books on the desk.",
            "There is + uncountable noun -> There is some milk in the fridge.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- There is / There are تستخدم للتعبير عن وجود شيء في مكان معين (يوجد/هناك).",
            "",
            "متى نستخدم There is ؟",
            "- مع الاسم المفرد القابل للعد (singular): There is a book…",
            "- مع الاسم غير القابل للعد (uncountable): There is some milk…",
            "",
            "متى نستخدم There are ؟",
            "- مع الاسم الجمع القابل للعد (plural): There are books…",
            "",
            "الصيغة العامة (للتثبيت):",
            "- There is + singular/uncountable + مكان",
            "- There are + plural + مكان",
            "",
            "ملاحظات مهمة (مستفادة من الملف):",
            "- بعض/any: some غالبًا في الإثبات، و any في النفي/الأسئلة.",
            "",
            "أخطاء شائعة:",
            "- There are a book ❌",
            "- There is books ❌",
          ],
        },
      ],
    },
    {
      id: "g2_05_prepositions_place",
      title: "5. Prepositions of place",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar Prepositions of place",
            "in (inside)",
            "on (on top)",
            "under (below)",
            "in front of",
            "behind",
            "next to",
            "above",
            "below",
            "between",
            "on the left",
            "opposite",
            "on the right",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- Prepositions of place تساعدك تصف (أين الشيء؟) بالنسبة لشيء آخر.",
            "",
            "🧠 طريقة تعلّم سريعة (سؤال واحد):",
            "- اسأل: Where is it? ثم اختر حرف الجر المناسب.",
            "",
            "🧩 معاني أهم الكلمات في هذا الدرس:",
            "- in = داخل",
            "- on = على (فوق سطح)",
            "- under = تحت",
            "- in front of = أمام",
            "- behind = خلف",
            "- next to = بجانب",
            "- above = أعلى من (ليس بالضرورة على سطح)",
            "- below = أسفل من",
            "- between = بين",
            "- on the left / on the right = على اليسار / على اليمين",
            "- opposite = مقابل",
            "",
            "⚠️ أخطاء شائعة:",
            "- الخلط بين on و above (on فوق سطح مباشرة، أما above قد يكون أعلى بدون ملامسة). ❗",
            "",
            "فكرة تثبيت: المكان = علاقة بين شيئين، مو كلمة حفظ فقط.",
          ],
        },
      ],
    },
    {
      id: "g2_06_plural_nouns_short",
      title: "6. Plural nouns",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar Plural nouns",
            "Regular Nouns (add -S)",
            "1 car -> 2 cars",
            "1 dog -> 2 dogs",
            "1 book -> 2 books",
            "1 house -> 2 houses",
            "1 apple -> 2 apples",
            "Ends in S, CH, SH, X or Z (add -ES) …",
            "Ends in F or FE (remove F/FE add -VES) …",
            "Ends in VOWEL + Y (add -S) …",
            "Ends in CONSONANT + Y (remove Y add -IES) …",
            "Irregular Nouns …",
            "Ends in VOWEL + O (add -S) …",
            "Ends in CONSONANT + O (add -ES) …",
            "No Change …",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- Plural nouns = تحويل الاسم من مفرد إلى جمع.",
            "",
            "🧩 القاعدة الأولى (من نص الدرس):",
            "- غالبًا نضيف -s: car → cars / dog → dogs / book → books",
            "",
            "🧠 متى نضيف -es؟ (كما ذُكر في النص):",
            "- إذا انتهت الكلمة بـ S / CH / SH / X / Z نضيف -ES ❗ (النص وضع نقاط (…) لذلك الأمثلة غير مذكورة هنا).",
            "",
            "🧠 تغييرات شائعة أخرى (كما ذُكر في النص):",
            "- F/FE تتحول إلى -VES ❗",
            "- consonant + Y تتحول إلى -IES ❗",
            "- vowel + Y نضيف -S",
            "- vowel + O نضيف -S ❗",
            "- consonant + O نضيف -ES ❗",
            "- Irregular / No change موجودة كفكرة في النص لكن بدون أمثلة هنا ❗",
            "",
            "⚠️ ملاحظة مهمة:",
            "- وجود (…) يعني أن المحتوى الأصلي مختصر؛ لذلك نوضح القاعدة بدون اختراع أمثلة جديدة.",
            "",
            "فكرة تثبيت: ابدأ بـ +s ثم انتقل للاستثناءات.",
          ],
        },
      ],
    },
    {
      id: "g2_07_this_that_these_those",
      title: "7. This, that, these, those",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar this, that, these, those",
            "This (singular, near)",
            "I like this apple.",
            "That (singular, far)",
            "I like that apple.",
            "These (plural, near)",
            "I like these apples.",
            "Those (plural, far)",
            "I like those apples.",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- هذه الكلمات اسمها Demonstratives: نستخدمها للإشارة لشيء مع تحديد (قريب/بعيد) و(مفرد/جمع).",
            "",
            "🧠 خريطة سريعة:",
            "- this = مفرد + قريب",
            "- that = مفرد + بعيد",
            "- these = جمع + قريب",
            "- those = جمع + بعيد",
            "",
            "✅ أمثلة من نص الدرس:",
            "- I like this apple.",
            "- I like that apple.",
            "- I like these apples.",
            "- I like those apples.",
            "",
            "⚠️ أخطاء شائعة:",
            "- استخدام this مع جمع (this apples) ❗",
            "- استخدام these مع مفرد (these apple) ❗",
            "",
            "فكرة تثبيت: This/These قريب — That/Those بعيد.",
          ],
        },
      ],
    },
    {
      id: "g2_08_present_simple",
      title: "8. Present simple",
      group: "Grammar 2 — Core",
      blocks: [
        {
          k: "EN",
          lines: [
            "Grammar present simple",
            "A present simple tense is a verb form of a sentence that tells about the action, circumstance which happens regularly, or occurrences.",
            "Affirmative: Subject + verb (s/es) + object",
            "Negative: Subject + do/does + not + verb + object",
            "Interrogative: Do/does + subject + verb + object + ?",
          ],
        },
        {
          k: "AR",
          lines: [
            "📘 متى نستخدم Present Simple؟",
            "- للروتين والعادات والأشياء المتكررة.",
            "- للحقائق العامة.",
            "",
            "🧩 التركيب من نص الدرس:",
            "- مثبت: Subject + verb (s/es) + object",
            "- منفي: Subject + do/does + not + verb + object",
            "- سؤال: Do/does + subject + verb + object + ?",
            "",
            "🧠 نقطة مهمة:",
            "- (s/es) غالبًا مع he / she / it في الجملة المثبتة.",
            "- في النفي والسؤال نستخدم do/does والفعل يبقى مصدر.",
            "",
            "⚠️ أخطاء شائعة:",
            "- He does plays ❌ (الصحيح: He plays / He doesn't play). ❗",
            "",
            "فكرة تثبيت: do/does = مفتاح النفي والسؤال.",
          ],
        },
        { k: "SRC", lines: ["onlymyenglish.com"] },
      ],
    },
    {
      id: "g2_09_capital_letters",
      title: "9. Capital letters",
      group: "Grammar 2 — Writing",
      blocks: [
        { k: "EN", lines: ["Writing Skill capital letters", "Start every sentence with a capital letter.", "Names, titles, days, months, places, nationalities, organizations, headings, books/films."] },
        {
          k: "AR",
          lines: [
            "📘 لماذا نستخدم Capital letters؟",
            "- لأنها قاعدة كتابة (Writing Skill) تجعل الجملة صحيحة وواضحة.",
            "",
            "🧩 متى نكتب حرف كبير؟ (من نص الدرس):",
            "- بداية كل جملة.",
            "- الأسماء (Names) والعناوين (titles).",
            "- الأيام (days) والأشهر (months).",
            "- الأماكن (places) والجنسيات (nationalities).",
            "- المنظمات (organizations).",
            "- العناوين (headings).",
            "- أسماء الكتب/الأفلام (books/films).",
            "",
            "⚠️ خطأ شائع:",
            "- نسيان الحرف الكبير في بداية الجملة.",
            "",
            "فكرة تثبيت: Capital = بداية جملة أو اسم علم.",
          ],
        },
      ],
    },
    {
      id: "g2_10_like_love_ing",
      title: "10. Like/love + noun / -ing",
      group: "Grammar 2 — Core",
      blocks: [
        { k: "EN", lines: ["Grammar like/love +noun/-ing form", "I / YOU / WE / THEY | LIKE / DON'T LIKE | DANCING. / RUNNING.", "HE / SHE / IT | LIKES / DOESN'T LIKE | GOING FOR WALKS. / SINGING."] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- بعد like / love يمكن أن يأتي:",
            "  - اسم (noun)",
            "  - أو فعل + ing (مثل dancing / running).",
            "",
            "🧩 التوافق مع الضمير (من نص الدرس):",
            "- I / you / we / they: like / don't like",
            "- he / she / it: likes / doesn't like",
            "",
            "✅ أمثلة من نص الدرس:",
            "- I like dancing.",
            "- He likes going for walks.",
            "",
            "⚠️ أخطاء شائعة:",
            "- نسيان s مع he/she/it: He like ❌",
            "- استخدام doesn't مع I/you/we/they ❗",
            "",
            "فكرة تثبيت: he/she/it = likes (وفي النفي doesn't).",
          ],
        },
      ],
    },
    {
      id: "g2_11_past_simple",
      title: "11. Past Simple – regular and irregular verbs",
      group: "Grammar 2 — Tenses",
      blocks: [
        { k: "EN", lines: ["Grammar Past Simple", "Regular verbs: add -ed", "I worked yesterday.", "She played football.", "Irregular verbs: special forms", "I went to school.", "He saw a movie.", "Negative: did + not + base verb", "I did not (didn’t) work yesterday.", "Interrogative: Did + subject + base verb + ?", "Did you go to school?"] },
        {
          k: "AR",
          lines: [
            "📘 متى نستخدم Past Simple؟",
            "- للتحدث عن حدث انتهى في الماضي (مثل yesterday / last week / ago).",
            "",
            "🧩 نوعان من الأفعال في الماضي (كما في نص الدرس):",
            "- Regular verbs: نضيف -ed (worked / played).",
            "- Irregular verbs: لها شكل خاص (went / saw).",
            "",
            "🧠 النفي والسؤال (المفتاح: did):",
            "- نفي: did + not + base verb",
            "- سؤال: Did + subject + base verb + ?",
            "مهم: بعد did الفعل يرجع للمصدر (بدون ed).",
            "",
            "✅ أمثلة من الدرس:",
            "- I worked yesterday.",
            "- I went to school.",
            "- I did not (didn’t) work yesterday.",
            "- Did you go to school?",
            "",
            "⚠️ أخطاء شائعة:",
            "- كتابة الفعل بالماضي بعد did (مثل: did went / didn’t worked) ❗",
            "",
            "فكرة تثبيت: did = يخلّي الفعل يرجع base.",
          ],
        },
      ],
    },
    {
      id: "g2_12_future_will",
      title: "12. Future with will",
      group: "Grammar 2 — Future",
      blocks: [
        { k: "EN", lines: ["Grammar Future with will", "Affirmative: Subject + will + verb", "I will study tomorrow.", "Negative: Subject + will not (won’t) + verb", "I will not (won’t) go to the park.", "Interrogative: Will + subject + verb + ?", "Will you help me?"] },
        {
          k: "AR",
          lines: [
            "📘 متى نستخدم will؟",
            "- للتوقع/قرار سريع/وعد/شيء سيحدث لاحقًا (حسب سياق الجملة).",
            "",
            "🧩 التركيب من نص الدرس:",
            "- مثبت: Subject + will + verb",
            "- منفي: Subject + will not (won’t) + verb",
            "- سؤال: Will + subject + verb + ?",
            "",
            "✅ أمثلة من الدرس:",
            "- I will study tomorrow.",
            "- I will not (won’t) go to the park.",
            "- Will you help me?",
            "",
            "⚠️ أخطاء شائعة:",
            "- إضافة (s) بعد will (مثل: he will goes) ❗",
            "- وضع to بعد will (مثل: will to go) ❗",
            "",
            "فكرة تثبيت: بعد will دائمًا فعل مصدر.",
          ],
        },
      ],
    },
    {
      id: "g2_13_can_ability",
      title: "13. Can / Can’t (ability)",
      group: "Grammar 2 — Modals",
      blocks: [
        { k: "EN", lines: ["Grammar Can / Can’t", "Affirmative: I/You/We/They/He/She/It + can + verb", "I can swim.", "Negative: … + cannot / can’t + verb", "He can’t drive.", "Question: Can + subject + verb + ?", "Can you speak English?"] },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- Can تستخدم للتعبير عن القدرة/المهارة: (يستطيع).",
            "- Can't (cannot) للنفي: (لا يستطيع).",
            "",
            "الصيغة (من أسلوب الملف):",
            "- Affirmative: Subject + can + Base verb",
            "- Negative: Subject + can’t + Base verb",
            "- Question: ? Can + Subject + Base verb",
            "",
            "ملاحظات مهمة:",
            "- بعد can/can’t الفعل يبقى بصيغته الأساسية (بدون s وبدون ing وبدون to).",
            "",
            "✅ من نص الدرس:",
            "- I can swim.",
            "- He can’t drive.",
            "- Can you speak English?",
          ],
        },
      ],
    },
    {
      id: "g2_14_articles_a_an_the",
      title: "14. Articles – a, an, the",
      group: "Grammar 2 — Nouns",
      blocks: [
        { k: "EN", lines: ["Grammar Articles", "a: before singular nouns starting with consonant sound", "a book, a car", "an: before singular nouns starting with vowel sound", "an apple, an orange", "the: specific or known nouns", "the sun, the teacher"] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- a / an: مع اسم مفرد غير محدد (أول مرة/بشكل عام).",
            "- the: مع شيء محدد/معروف للطرفين أو شيء فريد.",
            "",
            "🧠 الفرق بين a و an (الصوت وليس الحرف):",
            "- a قبل صوت ساكن (consonant sound).",
            "- an قبل صوت حرف علة (vowel sound).",
            "",
            "✅ من نص الدرس:",
            "- a book, a car",
            "- an apple, an orange",
            "- the sun, the teacher",
            "",
            "⚠️ أخطاء شائعة:",
            "- اختيار a/an حسب أول حرف مكتوب بدل أول صوت ❗",
            "",
            "فكرة تثبيت: a/an = واحد غير محدد، the = شيء محدد.",
          ],
        },
      ],
    },
    {
      id: "g2_15_comp_super_short",
      title: "15. Comparatives and superlatives",
      group: "Grammar 2 — Adjectives",
      blocks: [
        { k: "EN", lines: ["Grammar Comparatives and Superlatives", "Comparative: adjective + er / more + adjective", "tall → taller, beautiful → more beautiful", "Superlative: adjective + est / most + adjective", "tall → tallest, beautiful → most beautiful", "Irregular: good → better → best, bad → worse → worst"] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- Comparative = مقارنة بين شيئين (A vs B).",
            "- Superlative = الأفضل/الأعلى داخل مجموعة (A هو رقم 1 بين عدة أشياء).",
            "",
            "🧠 متى أستخدم كل واحد؟",
            "- Comparative عندما يوجد (than) أو مقارنة مباشرة: أكبر من / أسرع من …",
            "- Superlative عندما نقول: الأكبر/الأسرع/الأجمل بين الكل (غالبًا مع the).",
            "",
            "🧩 القاعدة (كما في نص الدرس):",
            "- Comparative: adjective + er  (للصفات القصيرة)  أو  more + adjective (للصفات الطويلة).",
            "- Superlative: adjective + est (للصفات القصيرة)  أو  most + adjective (للصفات الطويلة).",
            "",
            "✅ أمثلة من الدرس (تحويل مباشر):",
            "- tall → taller (Comparative)",
            "- tall → tallest (Superlative)",
            "- beautiful → more beautiful (Comparative)",
            "- beautiful → most beautiful (Superlative)",
            "",
            "⭐ الصفات الشاذة (Irregular) — لازم حفظها لأنها لا تتبع القاعدة:",
            "- good → better → best",
            "- bad → worse → worst",
            "",
            "⚠️ أخطاء شائعة:",
            "- استخدام more مع صفة قصيرة بشكل غير لازم (مثل: more tall) ❗",
            "- نسيان the مع superlative في كثير من الجمل (مثل: the tallest) ❗",
            "",
            "فكرة تثبيت:",
            "- إذا تقارن بين 2 → Comparative.",
            "- إذا تختار رقم 1 في مجموعة → Superlative.",
          ],
        },
      ],
    },
    {
      id: "g2_16_present_continuous",
      title: "16. Present continuous (be + verb-ing)",
      group: "Grammar 2 — Tenses",
      blocks: [
        { k: "EN", lines: ["Grammar Present Continuous", "Affirmative: Subject + am/is/are + verb-ing", "I am reading.", "She is cooking.", "Negative: Subject + am/is/are + not + verb-ing", "He is not sleeping.", "Question: Am/Is/Are + subject + verb-ing + ?", "Are they playing football?"] },
        {
          k: "AR",
          lines: [
            "📘 متى نستخدم Present Continuous؟",
            "- لوصف فعل يحدث الآن (في هذه اللحظة) أو حول الآن.",
            "",
            "🧩 التركيب من نص الدرس:",
            "- مثبت: Subject + am/is/are + verb-ing",
            "- منفي: Subject + am/is/are + not + verb-ing",
            "- سؤال: Am/Is/Are + subject + verb-ing + ?",
            "",
            "✅ أمثلة من الدرس:",
            "- I am reading.",
            "- She is cooking.",
            "- He is not sleeping.",
            "- Are they playing football?",
            "",
            "⚠️ أخطاء شائعة:",
            "- نسيان فعل be (مثل: I reading) ❗",
            "- استخدام ing بدون معنى “الآن” (حسب السياق) ❗",
            "",
            "فكرة تثبيت: be + ing = “قاعد/جالس يسوي الآن”.",
          ],
        },
      ],
    },
    {
      id: "g2_17_adverbs_frequency",
      title: "17. Adverbs of frequency",
      group: "Grammar 2 — Core",
      blocks: [
        { k: "EN", lines: ["Grammar Adverbs of Frequency", "always, usually, often, sometimes, rarely, never", "Placement: before the main verb, after be", "I always eat breakfast.", "She is never late."] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- ظروف التكرار تخبرنا: كم مرة يحدث الفعل؟",
            "",
            "🧠 أين مكانها في الجملة؟ (من نص الدرس):",
            "- قبل الفعل الرئيسي: I always eat breakfast.",
            "- بعد فعل be: She is never late.",
            "",
            "⚠️ أخطاء شائعة:",
            "- وضع الظرف في نهاية الجملة دائمًا (ليس قاعدة ثابتة) ❗",
            "",
            "فكرة تثبيت: قبل الفعل الرئيسي، وبعد be.",
          ],
        },
      ],
    },
    {
      id: "g2_18_question_words",
      title: "18. Question words",
      group: "Grammar 2 — Questions",
      blocks: [
        { k: "EN", lines: ["Grammar Question words", "Who – person", "What – thing", "Where – place", "When – time", "Why – reason", "How – manner / method", "Example:", "Who is she?", "Where do you live?", "Why is he sad?"] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- كلمات السؤال تحدد نوع الإجابة المطلوبة.",
            "",
            "🧠 المعاني (من نص الدرس):",
            "- Who: شخص",
            "- What: شيء/معلومة",
            "- Where: مكان",
            "- When: وقت",
            "- Why: سبب",
            "- How: طريقة/كيف",
            "",
            "✅ أمثلة من الدرس:",
            "- Who is she?",
            "- Where do you live?",
            "- Why is he sad?",
            "",
            "فكرة تثبيت: اختر كلمة السؤال حسب نوع المعلومة.",
          ],
        },
      ],
    },
    {
      id: "g2_19_should_must",
      title: "19. Modal verbs: should / must",
      group: "Grammar 2 — Modals",
      blocks: [
        { k: "EN", lines: ["Grammar Modal verbs: should / must", "Should: advice / recommendation", "You should eat more vegetables.", "Must: obligation / necessity", "You must wear a seatbelt.", "Negative: shouldn’t / mustn’t", "You shouldn’t lie.", "You mustn’t smoke here.", "Question: Should / Must + subject + verb + ?", "Should I call him?"] },
        {
          k: "AR",
          lines: [
            "📘 المعنى:",
            "- should = نصيحة/اقتراح (الأفضل تعمل كذا).",
            "- must = إلزام/ضرورة (لازم تعمل كذا).",
            "",
            "✅ من نص الدرس:",
            "- You should eat more vegetables.",
            "- You must wear a seatbelt.",
            "",
            "🧠 النفي:",
            "- shouldn’t = ليس من الأفضل/لا يُنصح.",
            "- mustn’t = ممنوع (منع قوي).",
            "",
            "✅ مثال من الدرس:",
            "- You mustn’t smoke here.",
            "",
            "🧩 السؤال:",
            "- Should / Must + subject + verb + ?",
            "- Should I call him?",
            "",
            "فكرة تثبيت: should = نصيحة، must = إلزام، mustn’t = ممنوع.",
          ],
        },
      ],
    },
    {
      id: "g2_20_some_any_much_many",
      title: "20. Some / Any / Much / Many / A lot of",
      group: "Grammar 2 — Quantifiers",
      blocks: [
        { k: "EN", lines: ["Grammar Some / Any / Much / Many / A lot of", "Some: affirmative sentences", "I have some friends.", "Any: negative / questions", "I don’t have any money.", "Do you have any questions?", "Much: uncountable (negative / questions)", "How much water?", "Many: countable (negative / questions)", "How many apples?", "A lot of: positive sentences, both countable & uncountable", "I have a lot of books.", "There is a lot of milk."] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- كلمات كمية تساعدنا نحدد مقدار/عدد شيء.",
            "",
            "🧠 الاستخدام (من نص الدرس):",
            "- some: غالبًا في الجمل المثبتة: I have some friends.",
            "- any: في النفي والأسئلة: I don’t have any money. / Do you have any questions?",
            "",
            "🧩 الفرق بين much و many:",
            "- much: مع غير المعدود (uncountable) غالبًا في النفي/السؤال: How much water?",
            "- many: مع المعدود جمع (countable plural) غالبًا في النفي/السؤال: How many apples?",
            "",
            "✅ a lot of:",
            "- تستخدم مع الاثنين (countable & uncountable):",
            "- I have a lot of books. / There is a lot of milk.",
            "",
            "⚠️ أخطاء شائعة:",
            "- خلط much مع المعدود أو many مع غير المعدود ❗",
            "",
            "فكرة تثبيت: many=عدد، much=كمية.",
          ],
        },
      ],
    },
    // Units 21–32 as sent (keep as-is)
    {
      id: "g2_u21_possessive",
      title: "Unit 21: Possessive 's and Possessive Adjectives",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        { k: "EN", lines: ["POSSESSIVE ADJECTIVES", "Subject Pronoun + verb:", "I", "You", "He", "She", "It", "We", "You", "They", "Example: I am a teacher.", "Possessive Adjective + noun:", "my", "your", "his", "her", "its", "our", "your", "their", "Example: These are my shoes."] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- هذا الدرس يعرض الصفات الملكية (Possessive Adjectives) ومعناها بالعربي.",
            "",
            "🧩 القاعدة:",
            "- الصفة الملكية تأتي قبل الاسم مباشرة.",
            "",
            "✅ (النص كما أُرسل — بدون حذف):",
            "الصفات الملكية",
            "الضمير + الفعل:",
            "أنا",
            "أنت",
            "هو",
            "هي",
            "هو/هي لغير العاقل",
            "نحن",
            "أنتم",
            "هم",
            "مثال: أنا معلم.",
            "الصفة الملكية + الاسم:",
            "لي / خاصتي",
            "لك / خاصتك",
            "له",
            "لها",
            "له/لها لغير العاقل",
            "لنا",
            "لكم",
            "لهم",
            "مثال: هذه حذائي.",
            "",
            "فكرة تثبيت: ملكية = كلمة قبل الاسم.",
          ],
        },
        { k: "SRC", lines: ["Source: 7ESL.COM"] },
      ],
    },
    {
      id: "g2_u22_and_but",
      title: "Unit 22: And / But",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        { k: "EN", lines: ["Coordinating conjunctions link similar words or word groups.", "and: links similar (or like) ideas.", "I like apples and bananas.", "or: links alternative ideas.", "Do you want an apple or a banana?", "but: links contrasting ideas.", "I like apples but I don't like bananas."] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- هذه روابط تنسيقية تربط فكرتين داخل نفس الجملة.",
            "",
            "✅ (النص كما أُرسل — بدون حذف):",
            "الروابط التنسيقية تصل الكلمات المتشابهة أو مجموعات الكلمات.",
            "و (and): تربط أفكار مشابهة أو متقاربة.",
            "أحب التفاح والموز.",
            "أو (or): تربط أفكار بديلة.",
            "هل تريد تفاحة أم موزة؟",
            "لكن (but): تربط أفكار متناقضة.",
            "أحب التفاح لكن لا أحب الموز.",
            "",
            "فكرة تثبيت: and إضافة — or خيار — but عكس.",
          ],
        },
      ],
    },
    {
      id: "g2_u23_there_is_are_as_sent",
      title: "Unit 23: There is / There are (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "GRAMMAR: THERE IS - THERE ARE",
            "Meaning: To say that something exists (or doesn't exist)",
            "AFFIRMATIVE:",
            "There is + singular noun -> There is a book on the desk.",
            "There are + plural noun -> There are books on the desk.",
            "There is + uncountable noun -> There is some milk in the fridge.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- There is/There are للتعبير عن وجود شيء (يوجد/هناك).",
            "",
            "متى نستخدم There is ؟",
            "- مع مفرد قابل للعد + مع غير المعدود.",
            "",
            "متى نستخدم There are ؟",
            "- مع جمع قابل للعد.",
            "",
            "مثال واحد لكل فكرة (من نفس النص):",
            "- There is a book on the desk.",
            "- There are books on the desk.",
            "- There is some milk in the fridge.",
          ],
        },
      ],
    },
    {
      id: "g2_u24_prepositions_place_as_sent",
      title: "Unit 24: Prepositions of Place (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "in (inside the box)",
            "on (on top of the box)",
            "under (under the box)",
            "in front of (in front of the box)",
            "behind (behind the box)",
            "next to (next to the box)",
            "above (أعلى من الصندوق)",
            "below (أسفل من الصندوق)",
            "between (بين صندوقين)",
            "on the left (على اليسار)",
            "opposite (مواجه لقطة أخرى)",
            "on the right (على اليمين)",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- حروف الجر للمكان تصف موقع شيء بالنسبة لشيء آخر.",
            "",
            "طريقة سهلة (زي أسلوب الملف):",
            "- اسأل: Where is it? ثم اختر الحرف المناسب.",
            "",
            "مثال واحد لكل فكرة (من نفس السطر الإنجليزي):",
            "- in (inside the box) = داخل الصندوق",
            "- on (on top of the box) = على الصندوق",
            "- under (under the box) = تحت الصندوق",
          ],
        },
      ],
    },
    {
      id: "g2_u25_plural_nouns_as_sent",
      title: "Unit 25: Plural Nouns (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "Regular Nouns (add -S): car → cars, dog → dogs",
            "Ends in S, CH, SH, X or Z (add -ES): bus → buses, match → matches",
            "Ends in F/FE (change to -VES): leaf → leaves, knife → knives",
            "Ends in vowel + Y (add -S): boy → boys",
            "Ends in consonant + Y (change to -IES): city → cities",
            "Irregular Nouns: man → men, child → children",
            "Ends in vowel + O (add -S): zoo → zoos",
            "Ends in consonant + O (add -ES): hero → heroes",
            "No change: sheep → sheep",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- للجمع قواعد: قاعدة عامة + استثناءات.",
            "",
            "القاعدة العامة:",
            "- غالبًا نضيف -s (car → cars).",
            "",
            "الاستثناءات (مثال واحد لكل نقطة من النص):",
            "- bus → buses (نضيف -es).",
            "- leaf → leaves (f/fe → ves).",
            "- city → cities (consonant + y → ies).",
            "- man → men (جمع شاذ).",
            "",
            "فكرة تثبيت:",
            "- احفظ الاستثناءات لأنها الأكثر تسببًا بالأخطاء.",
          ],
        },
      ],
    },
    {
      id: "g2_u26_this_that_as_sent",
      title: "Unit 26: This / That / These / Those (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "This (singular, near) → I like this apple.",
            "That (singular, far) → I like that apple.",
            "These (plural, near) → I like these apples.",
            "Those (plural, far) → I like those apples.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- كلمات إشارة تحدد (مفرد/جمع) و(قريب/بعيد).",
            "",
            "مثال واحد لكل نوع (من نفس النص):",
            "- this: I like this apple.",
            "- that: I like that apple.",
            "- these: I like these apples.",
            "- those: I like those apples.",
          ],
        },
      ],
    },
    {
      id: "g2_u28_going_to_as_sent",
      title: "Unit 28: Be going to (Plans / Future) (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "Affirmative: I am / You are / He is / We are / They are going to travel.",
            "Negative: I am not / You aren't / He isn't / We aren't / They aren't going to travel.",
            "Questions: Am I / Are you / Is he / Are we / Are they going to travel?",
            "Yes/No answers: Yes, I am. / No, I am not.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة (حسب أسلوب الملف):",
            "- be going to تستخدم لخطط/نية مستقبلية (قرار مسبق).",
            "",
            "الصيغ:",
            "- مثبت: am/is/are + going to + verb",
            "- منفي: am/is/are + not + going to + verb",
            "- سؤال: Am/Is/Are + subject + going to + verb ?",
            "",
            "مثال واحد (من النص):",
            "- I am going to travel.",
          ],
        },
      ],
    },
    {
      id: "g2_u29_infinitive_purpose_as_sent",
      title: "Unit 29: Infinitive of Purpose (To + Verb) (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "To show the purpose of an action.",
            "The students studied very hard to pass the exams.",
            "She is going to go to England to learn English.",
            "Negative: use \"not to\" → He changed his way not to see her.",
            "\"To\" can be at the start: To get a passport, firstly you should fill out this form.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- To + infinitive = لشرح الهدف/الغرض (Why?).",
            "",
            "الصيغة:",
            "- فعل + to + فعل مصدر",
            "",
            "مثال واحد (من النص):",
            "- The students studied very hard to pass the exams.",
            "",
            "ملاحظة مهمة:",
            "- النفي يكون (not to) وليس (to not). ❗",
          ],
        },
      ],
    },
    {
      id: "g2_u31_present_perfect_as_sent",
      title: "Unit 31: Present Perfect (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "Structure: have / has + past participle",
            "I have visited Paris.",
            "She has just finished her homework.",
            "Negative: have not / has not + past participle",
            "They haven't eaten yet.",
            "Questions: Have / Has + subject + past participle?",
            "Have you ever been to London?",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- Present Perfect يربط حدث بالماضي مع أثر/صلة بالحاضر.",
            "",
            "الصيغ (من النص):",
            "- مثبت: have/has + V3",
            "- منفي: have/has + not + V3",
            "- سؤال: Have/Has + subject + V3 ?",
            "",
            "مثال واحد (من النص):",
            "- I have visited Paris.",
          ],
        },
      ],
    },
    {
      id: "g2_u32_have_to_as_sent",
      title: "Unit 32: Have to / Don't have to (as sent)",
      group: "Grammar 2 — Units (as sent)",
      blocks: [
        {
          k: "EN",
          lines: [
            "Express necessity or obligation.",
            "I have to study for the test.",
            "Negative: I don't have to work today.",
            "Questions: Do I have to go?",
            "Short answers: Yes, you do. / No, you don't.",
          ],
        },
        {
          k: "AR",
          lines: [
            "شرح القاعدة:",
            "- have to = لازم/ضروري.",
            "- don't have to = ليس ضروري (اختياري).",
            "",
            "الصيغ (من النص):",
            "- مثبت: have/has to + verb",
            "- منفي: don't/doesn't have to + verb",
            "- سؤال: Do/Does + subject + have to + verb ?",
            "",
            "مثال واحد (من النص):",
            "- I have to study for the test.",
          ],
        },
      ],
    },
    // ... (يمكن إضافة باقي وحدات 23–32 هنا بنفس الأسلوب لاحقاً إذا احتجت نسخة "as-sent" كاملة)
    // Image lessons (as-is): (أضفنا نموذج واحد هنا كبداية)
    {
      id: "g2_img_adverbs_pyramid",
      title: "Image lesson: Grammar adverbs of frequency",
      group: "Grammar 2 — From images",
      blocks: [
        { k: "EN", lines: ["Grammar adverbs of frequency", "ADVERBS & EXPRESSIONS OF FREQUENCY", "100% ALWAYS", "90% USUALLY", "70% OFTEN", "50% SOMETIMES", "10% HARDLY EVER", "0% NEVER", "HOW OFTEN?", "every (day / week / month / year)", "Once / Twice / 3 times / 4 times a month"] },
        {
          k: "AR",
          lines: [
            "📘 الفكرة الأساسية:",
            "- هذه الصورة تعرض “مقياس/هرم” لظروف التكرار من 100% إلى 0%.",
            "",
            "🧠 كيف تستخدمها؟",
            "- اختر الظرف حسب نسبة تكرار الفعل:",
            "  - ALWAYS = دائمًا (100%)",
            "  - USUALLY = غالبًا (90%)",
            "  - OFTEN = كثيرًا (70%)",
            "  - SOMETIMES = أحيانًا (50%)",
            "  - HARDLY EVER = نادرًا جدًا (10%)",
            "  - NEVER = أبدًا (0%)",
            "",
            "🧩 سؤال مفتاحي في الصورة:",
            "- HOW OFTEN? = كم مرة؟",
            "",
            "🧩 تعبيرات زمنية (من الصورة):",
            "- every (day/week/month/year)",
            "- Once/Twice/3 times/4 times a month",
            "",
            "فكرة تثبيت: كلما ارتفعت النسبة اقتربت من ALWAYS.",
          ],
        },
      ],
    },
  ];
})();

